spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sushil
    username: root
    password: karkee
    validateOnQuery: SELECT 1
    testWhileIdle: true
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      
      
