spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sushil
    username: root
    password: karkee
    testWhileIdle: true
    validateOnQuery: SELECT 1
  data:
    database: MYSQL
    hibernate:
      ddl-auto: create
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
 
      
server:
  port: 9090
  #context-path: /api
  